services:
  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "3010:3010"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./upload_content:/app/temp
    entrypoint: sh -c "npm run start:dev"

  postgres:
    container_name: postgres-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=digitalplayer
    ports:
      - "5432:5432"
    volumes:
      - digitalplayer_pg_data:/var/lib/postgresql/data

volumes:
  digitalplayer_pg_data:
