FROM node:20-alpine

USER root

RUN apk add --no-cache ffmpeg
RUN apk add --no-cache nano

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node . .

RUN npm install

RUN npm run build

ENV NODE_ENV=prod

CMD [ "npm", "run", "start:prod" ]