FROM node:20-alpine

USER root

RUN apk add --no-cache ffmpeg \
    && apk add --no-cache nano \
    && apk add --no-cache python3 \
    && apk add --no-cache make g++  # Dependências para compilar o bcrypt

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node . .

RUN npm install

RUN npm run build

RUN npm rebuild bcrypt --build-from-source

ENV NODE_ENV=prod

CMD [ "npm", "run", "start:prod" ]
